config/routes.rb
Rails.application.routes.draw do
  resources :beers
  # get 'companies/index'
  # get 'companies/show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get         '/companies', to: 'companies#index', as: 'companies' # companies_path (Collection of companies)
  get         '/companies/:id', to: 'companies#show', as: 'company' # company_path (specific company)

  #   More Routes:
  # GET 	   /beers          =>	beers#index			(Load/display all beers)
  # GET 	   /beers/:id      =>	beers#show			(load/display 1 beer by id)/
  # GET 	   /beers/new      =>	beers#new  			(display a form to create a new beer)
  # POST 	   /bears          => beers#create 		(create a beer with POSTed data)
  # GET 	   /beers/:id/edit =>	beers#edit			(Display a form for editing a beer)
  # PATCH 	 /beers/:id 		 => beers#update 		(Update a beer with PATCHed data)
  # DELETE 	 /beers/:id 		 => beers#delete 		(delete a beer by ID)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/beer.rb
class Beer < ApplicationRecord
  belongs_to :company
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :beers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: %i[ show edit update destroy ]

  # GET /beers or /beers.json
  def index
    @beers = Beer.all
  end

  # GET /beers/1 or /beers/1.json
  def show
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers or /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to beer_url(@beer), notice: "Beer was successfully created." }
        format.json { render :show, status: :created, location: @beer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1 or /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to beer_url(@beer), notice: "Beer was successfully updated." }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1 or /beers/1.json
  def destroy
    @beer.destroy

    respond_to do |format|
      format.html { redirect_to beers_url, notice: "Beer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def beer_params
      params.require(:beer).permit(:name, :price, :description)
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/beers/_beer.html.erb
<div id="<%= dom_id beer %>">
  <p>
    <strong>Name:</strong>
    <%= beer.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= beer.price %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= beer.description %>
  </p>

</div>

app/views/beers/_form.html.erb
<%= form_with(model: beer) do |form| %>
  <% if beer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
        <% beer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing beer</h1>

<%= render "form", beer: @beer %>

<br>

<div>
  <%= link_to "Show this beer", @beer %> |
  <%= link_to "Back to beers", beers_path %>
</div>

app/views/beers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Beers</h1>

<div id="beers">
  <% @beers.each do |beer| %>
    <%= render beer %>
    <p>
      <%= link_to "Show this beer", beer %>
    </p>
  <% end %>
</div>

<%= link_to "New beer", new_beer_path %>

app/views/beers/new.html.erb
<h1>New beer</h1>

<%= render "form", beer: @beer %>

<br>

<div>
  <%= link_to "Back to beers", beers_path %>
</div>

app/views/beers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @beer %>

<div>
  <%= link_to "Edit this beer", edit_beer_path(@beer) %> |
  <%= link_to "Back to beers", beers_path %>

  <%= button_to "Destroy this beer", @beer, method: :delete %>
</div>

app/views/companies/index.html.erb
<h1>All Companies</h1>
<ul>
  <% @companies.each do |c| %>
    <li><%= link_to c.name, company_path(c) %></li>
  <% end %>
</ul>

<p>Find me in app/views/companies/index.html.erb</p>

app/views/companies/show.html.erb
<h1>Company Name: <%= @company.name %></h1>
<ul>
  <% @company.beers.each do |b| %>
  <li><%= link_to b.name, beer_path(b) %></li>
  <%end %>
</ul>

<p>Find me in app/views/companies/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeersOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>